### ISSUE TITLE
My Assets Page - a potential design

### ISSUE THREAD

**Issue by stephen94k** [wynddaoOld/dex-issue-tracker#11]
I think having IBC assets on the left and all CW-20 assets split into two separate columns on the same page is confusing.

I propose to have a single column to show assets with a selectable filter on the top to show (all, ibc only, CW-20) only that the user can click to filter.

Assets should always be shown in descending USD equivalent value. 

What do you guys think about this design recommendation vs the current split lay out?

![image](https://user-images.githubusercontent.com/95550193/209666183-a3fd8d22-f51c-4075-aa66-4cc80d63c4b5.png)

**Comment by WYNerD** [comment]
I personally think it's better to have them seperated. You can't IBC deposit CW20 Tokens e.g. , I think its better organized then other dexes. But I could be wrong :D

**Comment by WYNerD** [comment]
Well others are requesting the same thing. Let's do it.
