### ISSUE TITLE
Slippage Button

### ISSUE THREAD

**Issue by PavlovsBigBell** [wynddaoOld/dex-issue-tracker#13]
Remove the slippage button from the popup and put it as it;s own box to the top-right of the Swap page.  However it fits best and looks good from a UI perspective

**Comment by kyar1s** [comment]
Personally, I don't think this is better from a UI perspective. For several reasons:

- All exchanges have this option as a button with a wheel at the top right. We can see it in Osmosis, Pancake Swap, UniSwap, NomiSwap, even JunoSwap. So people who know how to modify this option know exactly where to find it.
- Now there is only the option to change the slippage, but in the future it can be enlarged and become a modal with more modification options, for example, adding a transaction deadline that reverses the transaction if the timeout is exceeded, or more.
- There are users who use swaps, but do not know what slippage is or the different options they can modify, and this is not a bad thing, as I do not think it is necessary for them to know in the first instance. Slippage is an automatic option that has a minimum of collateral if necessary. If we put it at first instance as a box with the option to modify the slippage before doing the operation, it may lead to confusion for not so expert users. We want simplicity in the swap for the user.
- And finally, and this is a totally subjective opinion, I think it is cleaner to have a button with a wheel than to have this box, from my perspective it looks weird, not good.

So, I've done this task, it's in a pull request but it hasn't been merged yet. And this is the result of what it looks like: 

![image](https://user-images.githubusercontent.com/45215699/211497631-92f00ee1-0089-45ca-9ed8-57ed70edacfd.png)

Please let me know your thoughts about this. Do you like how it looks like? Should I merge ?

@PavlovsBigBell @WYNerD @abefernan

**Comment by WYNerD** [comment]
Just do the task pls

**Comment by PavlovsBigBell** [comment]
Yes let's hold off on this update and keep it as is.  Could always come back to this topic if there is user feedback about it after launch.
