### ISSUE TITLE
Add LP "Max" issue

### ISSUE THREAD

**Issue by stephen94k** [wynddaoOld/dex-issue-tracker#14]
When adding "Max" LP, only the minimum of the two should be max. In this example screenshot, when I hit MAX next to Juno, it tries to add to the LP 16.3k WYND tokens which is too much. There needs to be logic to check counter pair token balance as a constraint
See screenshot 1:

Screenshot 1:
![image](https://user-images.githubusercontent.com/95550193/209666737-81545d24-fdc2-4ffa-be89-4d94ecd4181f.png)

When I hit "Max" next to "yndex" it displays the correct amount.

Screenshot 2:
![image](https://user-images.githubusercontent.com/95550193/209667067-de97211c-1cb1-454f-879d-7548981a2465.png)

### Realistically, we only need one single "Max" button and not two, because the max add amount should be exactly the same amount for both. I propose removing one of the max buttons and create a larger "Max" button

**Comment by stephen94k** [comment]
![image](https://user-images.githubusercontent.com/95550193/209668309-1ed19dad-f188-4181-b448-39e4eaf6f14e.png)
Another secondary issue is that the MAX amount is literally 100% of the balance.

While this is not an issue with the DEX right now because there is no trading, during live scenarios this may be problematic because as trades happen between when they click it and approve the TX, the price differential caused by others' trades will cause a pricing imbalance.

We either need to have some sort of built-in "slippage" feature OR we make MAX = 99.5%, so there is always some token left in case the price moves in between those actions.

We also want to have some safeguards so that the user can not do any actions that cause them to go below 0.1 JUNO in their account, including adding MAX liquidity. Otherwise, people will be running out of gas all the time.

**Comment by ethanfrey** [comment]
> While this is not an issue with the DEX right now because there is no trading, during live scenarios this may be problematic because as trades happen between when they click it and approve the TX, the price differential caused by others' trades will cause a pricing imbalance.

> We either need to have some sort of built-in "slippage" feature OR we make MAX = 99.5%, so there is always some token left in case the price moves in between those actions.

The contract handles this issue. You are right the max cannot be more than you have. But if you add 100% of your WYND tokens and there is some price change, the tx will not fail.

**Comment by ethanfrey** [comment]
> We also want to have some safeguards so that the user can not do any actions that cause them to go below 0.1 JUNO in their account, including adding MAX liquidity. Otherwise, people will be running out of gas all the time.

Very good point. We should do checks on swapping from JUNO or depositing JUNO in a pool to reserve some amount. Or whatever the gas token is (JUNOX on the testnet)
