### ISSUE TITLE
Refresh Page after swap

### ISSUE THREAD

**Issue by PavlovsBigBell** [wynddaoOld/dex-issue-tracker#15]
When I swapped to, the new balances did not appear when I went to deposit liquidity into a pool.  I needed to manually refresh the page. 

Should fix where the page automatically refreshes after swapping to give balances updated.

**Comment by PavlovsBigBell** [comment]
Also, after claiming unbonded tokens the available LP balance did not refresh.  This should also auto-refresh

**Comment by WYNerD** [comment]
Duplicate of #21. Let's merge this.
