### ISSUE TITLE
Better asset update

### ISSUE THREAD

**Issue by ethanfrey** [wynddaoOld/dex-issue-tracker#21]
I did a few swaps (Juno -> wynbex and tki), then went to the dashboard and the assets didn't show up.
I refreshed (ctrl-R) and the new assets were listed.

We should trigger asset update query after any swap (maybe with a 300ms delay as there is some delay between block committed and indexed in postgresql)

The display for adding to LP was also showing 0 WYNDEX after my trade until I refreshed (maybe same or different caching issue).

---

My use case: I arrived with Junox and usdcx
I swapped Juno for wyndex
I wanted to add to the juno-wyndex pool
It showed my balance as 0 and wouldn't let me

**Comment by ethanfrey** [comment]
Maybe a duplicate of #15 
Just check if that fix fixes this as well

**Comment by WYNerD** [comment]
> Also, after claiming unbonded tokens the available LP balance did not refresh. This should also auto-refresh

From #15
