### ISSUE TITLE
More safety checks on unbonding wizard

### ISSUE THREAD

**Issue by ethanfrey** [wynddaoOld/dex-issue-tracker#24]
The wizard is freaking awesome!

However, it should prevent me from doing stupid things.
I first bonded to 2 days
I then rebonded half from 2->1 days.
Then I clicked "manage" on the 1 days liquidity and it offered more to rebond up or to unstake.

Of course, these are both illegal and I could see that via "my pending rebondings".
But the wizard let me do it and then just showed "an error occurred"
It would be better if the wizard pulled the max from what was not rebounding and told me "All tokens are rebonding, you cannot unstake now" or something like that in this case.

**Comment by WYNerD** [comment]
#28 is a duplicate but has a screenshot, let's discuss there :)
