### ISSUE TITLE
[Low priority] [Performance] Clean up some  logs if they are not for support

### ISSUE THREAD

**Issue by apollo-pablo** [wynddaoOld/dex-issue-tracker#25]
> Problem

When starting up the web page, using chrome developers toolbox some logs appear. Also seems like repeated logs indicates, maybe a run race that can be avoid by a singleton.

> Tasks

- [ ] Research why repeated messages appear.
- [ ] Remove messages is they are not for support.

> Description

```
5 wallets are available!
932-cd1dac6f78014b7b.js:319 118 chains are available!
932-cd1dac6f78014b7b.js:319 5 wallets are available!
932-cd1dac6f78014b7b.js:319 118 chains are available!
932-cd1dac6f78014b7b.js:319 5 wallets are available!
932-cd1dac6f78014b7b.js:319 118 chains are available!
932-cd1dac6f78014b7b.js:319 5 wallets are available!
932-cd1dac6f78014b7b.js:319 118 chains are available!
932-cd1dac6f78014b7b.js:319 5 wallets are available!
932-cd1dac6f78014b7b.js:319 118 chains are available!
932-cd1dac6f78014b7b.js:319 5 wallets are available!
932-cd1dac6f78014b7b.js:319 118 chains are available!
```

**Comment by abefernan** [comment]
This comes from `cosmology-tech/cosmos-kit`'s `WalletManager`, we cannot disable it unless we edit the generated code and strip the `console.info`s before deploying.

**Comment by apollo-pablo** [comment]
With latest deploy I cant reproduce the repeated messages, it only appear now one time. If it is ok, we can close the issue. let me know.

![image](https://user-images.githubusercontent.com/95628259/210397948-391b57a9-416c-4abe-97ca-d193016cf3b6.png)

**Comment by abefernan** [comment]
I'd say it's ok, @WYNerD what do you think?
