### ISSUE TITLE
[Low-Priority] [UX] Specify on welcome screen a way the user can submit feedback

### ISSUE THREAD

**Issue by apollo-pablo** [wynddaoOld/dex-issue-tracker#26]
> Problem

On welcome screen, the following message is display: 

```
Your feedback is invaluable in helping us make sure the DEX runs smoothly. Thank you again for your support and understanding!
```

> Tasks

- [ ] Define how the user can submit a feedback. Could be discord issue bot.

**Comment by WYNerD** [comment]
This welcome screen is for testnet only. Once we go on mainnet the content is going to be the ToS.
