### ISSUE TITLE
[Dont know if Error] Leap Juno Testnet connection

### ISSUE THREAD

**Issue by apollo-pablo** [wynddaoOld/dex-issue-tracker#32]
> Problem

Being on juno testnet with leap wallet, a connect error appear.

![image](https://user-images.githubusercontent.com/95628259/210004741-6ec374b1-e390-4f16-91ad-9da805a713db.png)

![image](https://user-images.githubusercontent.com/95628259/210006321-5f87acf8-27bb-4923-b3e3-a570cf647416.png)

**Comment by abefernan** [comment]
Error no longer present in current deployment
