### ISSUE TITLE
Rebonding issue

### ISSUE THREAD

**Issue by PavlovsBigBell** [wynddaoOld/dex-issue-tracker#4]
When entering the LP tokens to rebond up or does, each number you type will exit the box.  You have to keep clicking every the box again each digit.  The 0 also does not automatically go away when you type.

**Comment by PavlovsBigBell** [comment]
The same thing happens when you try to unbond.  One digit at a time, 0 does not automatically go away

**Comment by WYNerD** [comment]
Fixed
