### ISSUE TITLE
[Low priority] [Staking] [Testnet] [Maybe not sure]

### ISSUE THREAD

**Issue by apollo-pablo** [wynddaoOld/dex-issue-tracker#40]
> Problem

Seems that doesnt allow to stake (**TWYND**) on testnet on latest testnet deploy. 
When pressing stake, no message, nor response return.

![image](https://user-images.githubusercontent.com/95628259/210829323-a31f2412-550a-4977-88a1-29045fe28e71.png)

**Comment by WYNerD** [comment]
Select a unbonding duration :D
