### ISSUE TITLE
No loading when unstaking

### ISSUE THREAD

**Issue by PavlovsBigBell** [wynddaoOld/dex-issue-tracker#5]
When you unstake, the Keplr window pops up as normal.  Once you approve, it waits for the next block like normal.

However, the Execute button does not show a loading icon and it will open a second Keplr window if you click it again.  See image (best I could do.  This is after you approve the Keplr popup). 
![No loading](https://user-images.githubusercontent.com/117847159/209454091-68655cfe-407d-4565-867b-1107c28836c5.png)

**Comment by WYNerD** [comment]
Fixed
