### ISSUE TITLE
Post unstaking bug 

### ISSUE THREAD

**Issue by PavlovsBigBell** [wynddaoOld/dex-issue-tracker#6]
Once you unstake, if you press the manage button again, it opens like this (this image) rather than going back to the normal rebond/unstake menu.  

Once you exit out and open again, it fixes itself.  Needs an autorefresh or something here.  
![After executing](https://user-images.githubusercontent.com/117847159/209454124-b382f21c-8bee-47b0-b3ef-637b88759778.png)

**Comment by PavlovsBigBell** [comment]
I had already unstaked the 0.5

**Comment by WYNerD** [comment]
#5

**Comment by WYNerD** [comment]
Fixed
